# Generated by Django 5.2.3 on 2025-06-17 12:53

import base.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_balance_userbalance_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="category",
            field=models.CharField(
                choices=base.enums.ShopCategoryEnum.choices,
                default="restaurant",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="accepted_payment_types",
            field=models.JSONField(
                blank=True, default=list, help_text="List of accepted payment methods"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, default="", max_length=150, unique=True),
        ),
    ]
