# Generated by Django 5.2.3 on 2025-06-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_shop_category_user_accepted_payment_types_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
