# Generated by Django 5.2.3 on 2025-06-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_user_full_name_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
