# Generated by Django 5.2.3 on 2025-06-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_user_full_name_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouporder",
            name="code",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
