# Generated by Django 5.2.3 on 2025-06-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_grouporder_code"),
        ("base", "0005_product_category"),
    ]

    operations = []
